FROM python:3.13-slim
WORKDIR /llm

COPY requirements.txt .
COPY mypy.ini .
COPY __init__.py .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

ENV DEBUG=false

CMD ["python", "worker.py"]