FROM python:3.13-slim
WORKDIR /llm

COPY requirements.txt .
COPY mypy.ini .
COPY __init__.py .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

ENV DEBUG=false

# -b bind the ip address and port to the app
# -k specifing the worker class to use
# gunicorn is a production server for running Python web applications
# uvicorn is an ASGI server worker for Python web applications

CMD ["gunicorn", "-b", "0.0.0.0:8000", "app.main:app", "-k", "uvicorn.workers.UvicornWorker", "--workers", "1", "--log-level", "debug"]