[mypy]
# -- Global options --
python_version = 3.11
warn_return_any = True
warn_unused_configs = True

# -- Strictness options --
# Enable these for more thorough checking as your codebase matures.
# disallow_untyped_defs = True
# disallow_any_unimported = True
# no_implicit_optional = True
# warn_redundant_casts = True
# warn_unused_ignores = True

# -- Per-module options for libraries without stubs --
# Mypy can complain about missing type information for some libraries.
# It's better to ignore them on a per-module basis than globally.
[mypy-numpy.*]
ignore_missing_imports = True
[mypy-faiss.*]
ignore_missing_imports = True
[mypy-unstructured.*]
ignore_missing_imports = True
[mypy-nest_asyncio.*]
ignore_missing_imports = True
[mypy-requests.*]
ignore_missing_imports = True