# Build step
FROM node:24-alpine AS build
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build

# Serve with nginx
FROM node:24-alpine AS run

WORKDIR /app
COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/node_modules ./node_modules

ENV PORT=80
EXPOSE 80

CMD ["node", "build"]