name: "step - deploy"
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      container_type:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      context_path:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      ACR_LOGIN_SERVER_NAME:
        required: true
      API_CONTAINER_NAME:
        required: true
      WEB_CONTAINER_NAME:
        required: true
      RESOURCE_GROUP:
        required: true

jobs:
  deploy:
    name: deploy ${{inputs.container_type}}
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set container name
        run: |
          if [ "${{ inputs.container_type }}" == "api" ]; then
            echo "CONTAINER_NAME=${{ secrets.API_CONTAINER_NAME }}" >> $GITHUB_ENV
          else
            echo "CONTAINER_NAME=${{ secrets.WEB_CONTAINER_NAME }}" >> $GITHUB_ENV
          fi
      - name: "azure login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{secrets.ACR_LOGIN_SERVER_NAME}}

      - name: Log a working directory
        run: echo "${{ github.workspace }}"

      - name: List contents of the working directory
        run: |
          echo "Current directory: $PWD"
          ls -R
        working-directory: ${{ github.workspace }}

      - name: Build and push ${{inputs.container_type}} image
        run: |
          docker build -t ${{secrets.ACR_LOGIN_SERVER_NAME}}.azurecr.io/$CONTAINER_NAME:latest ${{ inputs.dockerfile_path }}
          docker push ${{ secrets.ACR_LOGIN_SERVER_NAME }}.azurecr.io/$CONTAINER_NAME:latest
        working-directory: ${{ github.workspace }}${{ inputs.context_path }}

      - name: Update ${{inputs.container_type}} Container App image to trigger new revision
        run: |
          az containerapp update \
            --name $CONTAINER_NAME \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER_NAME }}.azurecr.io/$CONTAINER_NAME:latest
